---

name: prismatic_nompi

channels:
  - conda-forge

dependencies:
  - python = 3
  - boost
  - hdf5 >=1.10
  - fftw >=3.3
  - qt >=5
  - numpy >= 1.13.0
  - matplotlib >= 2.0.2
  - h5py >= 2.9.0
  - cmake
